experiment_name: "wav2vec-mlp"
tags:
  - mlp
  - functional-features
  - wav2vec
  - hidden-256-128-64
  - mlp-dropout-0.8
  - wd-1e-3
  - lr-1e-3
  - weighted-ce
  - label-smooth-0.1
  - adam
  - plateau
  - grad-clip-1.0
  - no-window
  - modality-wav2vec
  - audio

features:
  modality: "wav2vec"
  wav2vec_dim: 768

data:
  cleaned_data_root: "data"
  train_dir: "data/train"
  dev_dir: "data/dev"
  checkpoints_dir: "checkpoints"

scheduler:
  type: "plateau"
  mode: "min"
  factor: 0.5
  patience: 5
  min_lr: 0.000001

mlp:
  hidden_dims: [256, 128, 64]
  dropout: 0.8
  weight_decay: 0.001

training:
  model_type: "functional"
  num_classes: 2
  batch_size: 0
  num_workers: 0
  learning_rate: 0.001
  num_epochs: 200
  early_stopping_patience: 25
  grad_clip_norm: 1.0
  label_smoothing: 0.1
